apiVersion: apps/v1
kind: Deployment
metadata:
  name: majidapp-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: majidapp-3
  template:
    metadata:
      labels:
        app: majidapp-3
    spec:
      containers:
      - name: majidapp-3
        image:  majid343/gochat3:1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        readinessProbe: